name: diplom-dev

include:
  # Backend services (development mode)
  - path: ./backend/backend/docker-compose.dev.yaml

  # Frontend services - Admin (development mode)
  - path: ./frontend/admin/docker-compose.dev.yaml
    project_directory: ./frontend/admin

  # Frontend services - Seller (development mode)
  - path: ./frontend/seller/docker-compose.dev.yaml
    project_directory: ./frontend/seller

  # Frontend services - Buyer (development mode)
  - path: ./frontend/buyer/docker-compose.dev.yaml
    project_directory: ./frontend/buyer

  # Prosto Board Volume Main (production mode for now)
  - path: ./backend/prosto_board_volume-main/docker-compose.yaml
    project_directory: ./backend/prosto_board_volume-main

networks:
  diplom_default:
    name: diplom_default
    external: true
