name: diplom

include:
  # Backend services
  - path: ./backend/backend/docker-compose.yaml

  # Frontend services - Admin
  - path: ./frontend/admin/docker-compose.yaml

  # Frontend services - Seller
  - path: ./frontend/seller/docker-compose.yaml

  # Frontend services - Buyer
  - path: ./frontend/buyer/docker-compose.yaml

  # Prosto Board Volume Main
  - path: ./backend/prosto_board_volume-main/docker-compose.yaml

  # Keycloak Authentication Service
  - path: ./keycloak/docker-compose.yaml

  # Umami analitycs service
  - path: ./umami/docker-compose.yaml


networks:
  diplom_default:
    name: diplom_default
    external: true

