services:
  # Backend services - Always runs regardless of profile
  backend:
    extends:
      file: ./backend/backend/docker-compose.yaml
    ports:
      - "${BACKEND_PORT:-8000}:${BACKEND_PORT:-8000}"
    env_file:
      - .env
    networks:
      - diplom-network

  # Frontend services with profile selection
  admin-frontend:
    extends:
      file: ${COMPOSE_FILE_PATH:-./frontend/admin/docker-compose}${COMPOSE_FILE_EXT:-.yaml}
    ports:
      - "${FRONTEND_ADMIN_PORT:-${FRONTEND_PORT:-80}}:${CONTAINER_PORT:-80}"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    networks:
      - diplom-network

  seller-frontend:
    extends:
      file: ${COMPOSE_FILE_PATH:-./frontend/seller/docker-compose}${COMPOSE_FILE_EXT:-.yaml}
    ports:
      - "${FRONTEND_SELLER_PORT:-${FRONTEND_PORT:-80}}:${CONTAINER_PORT:-80}"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    networks:
      - diplom-network

  buyer-frontend:
    extends:
      file: ${COMPOSE_FILE_PATH:-./frontend/buyer/docker-compose}${COMPOSE_FILE_EXT:-.yaml}
    ports:
      - "${FRONTEND_BUYER_PORT:-${FRONTEND_PORT:-80}}:${CONTAINER_PORT:-80}"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    networks:
      - diplom-network

volumes:
  backend-pg-data:
  backend-redis-data:

networks:
  diplom-network:
    driver: bridge
