services:
  buyer-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ${BUYER_FRONTEND_CONTAINER:-buyer-frontend-prod}
    ports:
      - "${BUYER_FRONTEND_PORT:-8082}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PRODUCTION_BUYER_HOST=${PRODUCTION_BUYER_HOST}
      - PRODUCTION_API_HOST=${PRODUCTION_API_HOST}
      - PRODUCTION_KEYCLOAK_HOST=${PRODUCTION_KEYCLOAK_HOST}
      - PRODUCTION_HOST=${PRODUCTION_HOST}
      - KEYCLOAK_HOST=${PRODUCTION_KEYCLOAK_HOST}
      - KEYCLOAK_PORT=${KEYCLOAK_PORT}
      - FRONTEND_PORT=${FRONTEND_PRODUCTION_PORT}
    networks:
      - diplom_default
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

networks:
  diplom_default:
    name: diplom_default
    external: true
