
services:
  buyer-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: buyer-frontend-dev
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=${FRONTEND_BUYER_PORT:-3000}
      - REACT_APP_API_URL=${FRONTEND_BUYER_API_URL:-http://localhost:8000}
      - REACT_APP_API_TIMEOUT=${FRONTEND_BUYER_API_TIMEOUT:-30000}
      - REACT_APP_ENABLE_ANALYTICS=${FRONTEND_BUYER_ENABLE_ANALYTICS:-false}
      - REACT_APP_ENABLE_DEBUG_TOOLS=${FRONTEND_BUYER_ENABLE_DEBUG_TOOLS:-false}
    ports:
      - "${FRONTEND_BUYER_PORT:-3000}:3000"
    restart: unless-stopped
    networks:
      - frontend-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  frontend-network:
    driver: bridge
