services:
  buyer-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
        REACT_APP_KEYCLOAK_URL: ${REACT_APP_KEYCLOAK_URL}
        REACT_APP_KEYCLOAK_REALM: ${REACT_APP_KEYCLOAK_REALM}
        REACT_APP_KEYCLOAK_CLIENT_ID: ${REACT_APP_KEYCLOAK_CLIENT_ID}
    container_name: buyer-frontend-prod
    ports:
      - "${BUYER_FRONTEND_PORT:-8082}:80"
    networks:
      - diplom_default
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always

networks:
  diplom_default:
    name: diplom_default
    external: true
