FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install development dependencies
COPY package*.json ./
RUN npm install

# Set environment variables
ENV NODE_ENV=development \
    PORT=3000

# Create non-root user
RUN addgroup -g 1001 -S nodejs && \
    adduser -S nodejs -u 1001 -G nodejs && \
    chown -R nodejs:nodejs /app

# Switch to non-root user
USER nodejs

# Expose port
EXPOSE 3000

# Command to run the application in development mode
CMD ["npm", "start"]
