services:
  buyer-frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: buyer-frontend-dev
    ports:
      - "${FRONTEND_BUYER_PORT:-8082}:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8000}
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=true
      - NODE_ENV=development
      - KEYCLOAK_HOST=${KEYCLOAK_HOST:-172.27.65.14}
      - KEYCLOAK_PORT=${KEYCLOAK_PORT:-8030}
      - FRONTEND_PORT=${FRONTEND_BUYER_PORT:-8082}
    networks:
      - diplom_default
    restart: always
    stdin_open: true
    tty: true

networks:
  diplom_default:
    name: diplom_default
    external: true
