version: '3.8'

services:
  buyer-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: buyer-frontend-dev
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=${FRONTEND_BUYER_PORT:-3000}
    ports:
      - "${FRONTEND_BUYER_PORT:-3000}:3000"
    restart: unless-stopped
    networks:
      - diplom-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  diplom-network:
    external: true
