# Development override for Docker Compose
# Use with: docker compose -f docker-compose.yaml -f docker-compose.dev.yaml up

services:
  api:
    # Development-specific configuration
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/backend
        - action: sync
          path: ./tests
          target: /app/tests
        - action: rebuild
          path: pyproject.toml
        - action: rebuild
          path: uv.lock
    # Enable debug mode for development
    environment:
      BACKEND_DEBUG: true
      BACKEND_RELOAD: true
      BACKEND_LOG_LEVEL: debug
