services:
  api:
    &api
    build:
      context: .
    image: backend:latest
    container_name: backend-api
    restart: always
    ports:
      - "${BACKEND_PORT:-8000}:${BACKEND_PORT:-8000}"
    depends_on:
      backend-pg:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      bash -c "
        echo '🔄 Running database migrations...' &&
        python -m alembic upgrade head &&
        echo '✅ Migrations completed successfully' &&
        echo '🚀 Starting FastAPI application...' &&
        python -m backend
      "
    environment:
      BACKEND_HOST: ${BACKEND_HOST:-0.0.0.0}
      BACKEND_PORT: ${BACKEND_PORT:-8000}
      BACKEND_DEBUG: ${BACKEND_DEBUG:-false}
      BACKEND_LOG_LEVEL: ${BACKEND_LOG_LEVEL:-info}
      BACKEND_RELOAD: ${BACKEND_RELOAD:-false}
      BACKEND_WORKERS: ${BACKEND_WORKERS:-1}
      BACKEND_CORS_ALLOW_ORIGINS: ${BACKEND_CORS_ALLOW_ORIGINS:-"*"}
      BACKEND_CORS_ALLOW_CREDENTIALS: ${BACKEND_CORS_ALLOW_CREDENTIALS:-True}
      BACKEND_CORS_ALLOW_METHODS: ${BACKEND_CORS_ALLOW_METHODS:-"*"}
      BACKEND_CORS_ALLOW_HEADERS: ${BACKEND_CORS_ALLOW_HEADERS:-"*"}
      BACKEND_UPLOADS_DIR: ${BACKEND_UPLOADS_DIR:-uploads}
      BACKEND_PROSTO_BOARD_VOLUME_SEG_URL: ${BACKEND_PROSTO_BOARD_VOLUME_SEG_URL:-http://yolo_backend:8001}
      POSTGRES_PASSWORD: ${BACKEND_PG_PASSWORD:-backend}
      POSTGRES_USER: ${BACKEND_PG_USER:-backend}
      POSTGRES_DB: ${BACKEND_PG_DATABASE:-backend}
    volumes:
      - ./migrations:/app/migrations
      - ./uploads:/app/uploads
    networks:
      - app_network
      - diplom_default
    restart: always


  backend-pg:
    image: postgres:17.4-bookworm
    hostname: backend-pg
    container_name: backend-pg
    environment:
      POSTGRES_PASSWORD: ${BACKEND_PG_PASSWORD:-backend}
      POSTGRES_USER: ${BACKEND_PG_USER:-backend}
      POSTGRES_DB: ${BACKEND_PG_DATABASE:-backend}
    volumes:
      - backend-pg-data:/var/lib/postgresql/data
    restart: always
    networks:
      - app_network
      - diplom_default
    healthcheck:
      test: pg_isready -U ${BACKEND_PG_USER:-backend}
      interval: 2s
      timeout: 3s
      retries: 40
    restart: always


  redis:
    image: bitnami/redis:7.4
    container_name: backend-redis
    ports:
      - "6379:6379"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: ${BACKEND_REDIS_PASSWORD:+"no"}${BACKEND_REDIS_PASSWORD:-"yes"}
      REDIS_PASSWORD: ${BACKEND_REDIS_PASSWORD:-""}
    networks:
      - app_network
      - diplom_default
    healthcheck:
      test: redis-cli ping
      interval: 2s
      timeout: 3s
      retries: 40
    volumes:
      - backend-redis-data:/bitnami/redis/data
    restart: always


volumes:
  backend-pg-data:
  backend-redis-data:

networks:
  app_network:
    driver: bridge
  diplom_default:
    name: diplom_default
    external: true
