"""make_chat_message_sender_ids_nullable

Revision ID: 0c1d40332141
Revises: 5de4831ef8fc
Create Date: 2025-06-14 18:21:03.283402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c1d40332141'
down_revision: Union[str, None] = '5de4831ef8fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Сначала делаем поля nullable
    op.alter_column('chat_message', 'buyer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('chat_message', 'seller_id',
               existing_type=sa.UUID(),
               nullable=True)

    # Теперь обновляем существующие данные согласно новой логике:
    # Если is_read_by_buyer = True и is_read_by_seller = False, то отправитель - buyer
    # Если is_read_by_seller = True и is_read_by_buyer = False, то отправитель - seller
    # Если оба True или оба False, то определяем по времени создания (четные - buyer, нечетные - seller)

    connection = op.get_bind()

    # Обновляем сообщения где четко видно, что отправитель - покупатель
    connection.execute(sa.text("""
        UPDATE chat_message
        SET seller_id = NULL
        WHERE is_read_by_buyer = true AND is_read_by_seller = false
    """))

    # Обновляем сообщения где четко видно, что отправитель - продавец
    connection.execute(sa.text("""
        UPDATE chat_message
        SET buyer_id = NULL
        WHERE is_read_by_seller = true AND is_read_by_buyer = false
    """))

    # Для остальных сообщений (где оба true или оба false) используем простую логику:
    # четные ID - от покупателя, нечетные - от продавца
    connection.execute(sa.text("""
        UPDATE chat_message
        SET seller_id = NULL
        WHERE (is_read_by_buyer = is_read_by_seller)
        AND (EXTRACT(EPOCH FROM created_at)::bigint % 2 = 0)
    """))

    connection.execute(sa.text("""
        UPDATE chat_message
        SET buyer_id = NULL
        WHERE (is_read_by_buyer = is_read_by_seller)
        AND (EXTRACT(EPOCH FROM created_at)::bigint % 2 = 1)
    """))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_message', 'seller_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('chat_message', 'buyer_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
