"""fix_wood_type_price_relationship

Revision ID: 5de4831ef8fc
Revises: 1342136898ea
Create Date: 2025-05-20 16:17:56.773015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de4831ef8fc'
down_revision: Union[str, None] = '1342136898ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
