"""

Revision ID: 935c8910b92e
Revises: 5de4831ef8fc
Create Date: 2025-06-06 12:38:01.918685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '935c8910b92e'
down_revision: Union[str, None] = '5de4831ef8fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyer', sa.Column('last_activity', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_buyer_last_activity'), 'buyer', ['last_activity'], unique=False)
    op.add_column('seller', sa.Column('last_activity', sa.DateTime(timezone=True), nullable=False))
    op.create_index(op.f('ix_seller_last_activity'), 'seller', ['last_activity'], unique=False)
    op.drop_constraint('wood_type_price_wood_type_id_fkey', 'wood_type_price', type_='foreignkey')
    op.create_foreign_key(None, 'wood_type_price', 'wood_type', ['wood_type_id'], ['id'], ondelete='CASCADE')
    op.add_column('wooden_board', sa.Column('length', sa.Float(), nullable=False, comment='Length in meters'))
    op.add_column('wooden_board', sa.Column('volume', sa.Float(), nullable=False, comment='Calculated volume in cubic meters'))
    op.add_column('wooden_board', sa.Column('confidence', sa.Float(), nullable=False, comment='AI detection confidence (0-1)'))
    op.add_column('wooden_board', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('wooden_board', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('wooden_board', sa.Column('product_id', sa.UUID(), nullable=False))
    op.alter_column('wooden_board', 'height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Height in meters',
               existing_nullable=False)
    op.alter_column('wooden_board', 'width',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Width in meters',
               existing_nullable=False)
    op.create_index(op.f('ix_wooden_board_product_id'), 'wooden_board', ['product_id'], unique=False)
    op.create_foreign_key(None, 'wooden_board', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('wooden_board', 'lenght')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wooden_board', sa.Column('lenght', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'wooden_board', type_='foreignkey')
    op.drop_index(op.f('ix_wooden_board_product_id'), table_name='wooden_board')
    op.alter_column('wooden_board', 'width',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Width in meters',
               existing_nullable=False)
    op.alter_column('wooden_board', 'height',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Height in meters',
               existing_nullable=False)
    op.drop_column('wooden_board', 'product_id')
    op.drop_column('wooden_board', 'updated_at')
    op.drop_column('wooden_board', 'created_at')
    op.drop_column('wooden_board', 'confidence')
    op.drop_column('wooden_board', 'volume')
    op.drop_column('wooden_board', 'length')
    op.drop_constraint(None, 'wood_type_price', type_='foreignkey')
    op.create_foreign_key('wood_type_price_wood_type_id_fkey', 'wood_type_price', 'wood_type_price', ['wood_type_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_seller_last_activity'), table_name='seller')
    op.drop_column('seller', 'last_activity')
    op.drop_index(op.f('ix_buyer_last_activity'), table_name='buyer')
    op.drop_column('buyer', 'last_activity')
    # ### end Alembic commands ###
