"""initial_migration

Revision ID: 1342136898ea
Revises: 
Create Date: 2025-05-20 15:28:33.905852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1342136898ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('keycloak_uuid', sa.UUID(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_id'), 'buyer', ['id'], unique=True)
    op.create_index(op.f('ix_buyer_is_online'), 'buyer', ['is_online'], unique=False)
    op.create_index(op.f('ix_buyer_keycloak_uuid'), 'buyer', ['keycloak_uuid'], unique=True)
    op.create_table('seller',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('keycloak_uuid', sa.UUID(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_id'), 'seller', ['id'], unique=True)
    op.create_index(op.f('ix_seller_is_online'), 'seller', ['is_online'], unique=False)
    op.create_index(op.f('ix_seller_keycloak_uuid'), 'seller', ['keycloak_uuid'], unique=True)
    op.create_table('wood_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('neme', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wood_type_id'), 'wood_type', ['id'], unique=True)
    op.create_index(op.f('ix_wood_type_neme'), 'wood_type', ['neme'], unique=True)
    op.create_table('wood_type_price',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('price_per_m3', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('wood_type_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['wood_type_id'], ['wood_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wood_type_price_id'), 'wood_type_price', ['id'], unique=True)
    op.create_index(op.f('ix_wood_type_price_price_per_m3'), 'wood_type_price', ['price_per_m3'], unique=False)
    op.create_index(op.f('ix_wood_type_price_wood_type_id'), 'wood_type_price', ['wood_type_id'], unique=False)
    op.create_table('chat_thread',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_thread_buyer_id'), 'chat_thread', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_chat_thread_id'), 'chat_thread', ['id'], unique=True)
    op.create_index(op.f('ix_chat_thread_seller_id'), 'chat_thread', ['seller_id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('descrioption', sa.String(), nullable=True),
    sa.Column('delivery_possible', sa.Boolean(), nullable=False),
    sa.Column('pickup_location', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('wood_type_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wood_type_id'], ['wood_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_delivery_possible'), 'product', ['delivery_possible'], unique=False)
    op.create_index(op.f('ix_product_id'), 'product', ['id'], unique=True)
    op.create_index(op.f('ix_product_pickup_location'), 'product', ['pickup_location'], unique=False)
    op.create_index(op.f('ix_product_price'), 'product', ['price'], unique=False)
    op.create_index(op.f('ix_product_seller_id'), 'product', ['seller_id'], unique=False)
    op.create_index(op.f('ix_product_title'), 'product', ['title'], unique=False)
    op.create_index(op.f('ix_product_volume'), 'product', ['volume'], unique=False)
    op.create_index(op.f('ix_product_wood_type_id'), 'product', ['wood_type_id'], unique=False)
    op.create_table('chat_message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read_by_buyer', sa.Boolean(), nullable=False),
    sa.Column('is_read_by_seller', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_thread.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_buyer_id'), 'chat_message', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_chat_message_id'), 'chat_message', ['id'], unique=True)
    op.create_index(op.f('ix_chat_message_seller_id'), 'chat_message', ['seller_id'], unique=False)
    op.create_index(op.f('ix_chat_message_thread_id'), 'chat_message', ['thread_id'], unique=False)
    op.create_table('image',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_id'), 'image', ['id'], unique=True)
    op.create_index(op.f('ix_image_image_path'), 'image', ['image_path'], unique=True)
    op.create_index(op.f('ix_image_product_id'), 'image', ['product_id'], unique=False)
    op.create_table('wooden_board',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('lenght', sa.Float(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wooden_board_id'), 'wooden_board', ['id'], unique=True)
    op.create_index(op.f('ix_wooden_board_image_id'), 'wooden_board', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wooden_board_image_id'), table_name='wooden_board')
    op.drop_index(op.f('ix_wooden_board_id'), table_name='wooden_board')
    op.drop_table('wooden_board')
    op.drop_index(op.f('ix_image_product_id'), table_name='image')
    op.drop_index(op.f('ix_image_image_path'), table_name='image')
    op.drop_index(op.f('ix_image_id'), table_name='image')
    op.drop_table('image')
    op.drop_index(op.f('ix_chat_message_thread_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_seller_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_buyer_id'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index(op.f('ix_product_wood_type_id'), table_name='product')
    op.drop_index(op.f('ix_product_volume'), table_name='product')
    op.drop_index(op.f('ix_product_title'), table_name='product')
    op.drop_index(op.f('ix_product_seller_id'), table_name='product')
    op.drop_index(op.f('ix_product_price'), table_name='product')
    op.drop_index(op.f('ix_product_pickup_location'), table_name='product')
    op.drop_index(op.f('ix_product_id'), table_name='product')
    op.drop_index(op.f('ix_product_delivery_possible'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_chat_thread_seller_id'), table_name='chat_thread')
    op.drop_index(op.f('ix_chat_thread_id'), table_name='chat_thread')
    op.drop_index(op.f('ix_chat_thread_buyer_id'), table_name='chat_thread')
    op.drop_table('chat_thread')
    op.drop_index(op.f('ix_wood_type_price_wood_type_id'), table_name='wood_type_price')
    op.drop_index(op.f('ix_wood_type_price_price_per_m3'), table_name='wood_type_price')
    op.drop_index(op.f('ix_wood_type_price_id'), table_name='wood_type_price')
    op.drop_table('wood_type_price')
    op.drop_index(op.f('ix_wood_type_neme'), table_name='wood_type')
    op.drop_index(op.f('ix_wood_type_id'), table_name='wood_type')
    op.drop_table('wood_type')
    op.drop_index(op.f('ix_seller_keycloak_uuid'), table_name='seller')
    op.drop_index(op.f('ix_seller_is_online'), table_name='seller')
    op.drop_index(op.f('ix_seller_id'), table_name='seller')
    op.drop_table('seller')
    op.drop_index(op.f('ix_buyer_keycloak_uuid'), table_name='buyer')
    op.drop_index(op.f('ix_buyer_is_online'), table_name='buyer')
    op.drop_index(op.f('ix_buyer_id'), table_name='buyer')
    op.drop_table('buyer')
    # ### end Alembic commands ###
