services:
  keycloak-postgres:
    image: postgres:14-alpine
    container_name: ${KEYCLOAK_POSTGRES_CONTAINER:-keycloak-postgres-prod}
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-keycloak}
      POSTGRES_USER: ${POSTGRES_USER:-keycloak}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-change_me}
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    networks:
      - diplom_default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-keycloak} -d ${POSTGRES_DB:-keycloak}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: ${KEYCLOAK_CONTAINER:-keycloak-prod}
    environment:
      # Admin user and password for initial Keycloak setup (KC_BOOTSTRAP_*)
      # These are now also used by the setup-universal.sh script.
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD:-admin_password}
      # База данных
      KC_DB: postgres
      KC_DB_USERNAME: ${POSTGRES_USER:-keycloak}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-change_me}
      KC_DB_URL: jdbc:postgresql://${KEYCLOAK_POSTGRES_CONTAINER:-keycloak-postgres-prod}:5432/${POSTGRES_DB:-keycloak}
      # Хост и прокси (настройте по необходимости)
      KC_HOSTNAME: ${KC_HOSTNAME_URL:-localhost}
      KC_PROXY: ${KC_PROXY:-edge}
      KC_HTTP_ENABLED: "true"  # если нужен http, иначе false
    ports:
      - "${KEYCLOAK_EXTERNAL_PORT:-8030}:8080"
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    # command: # Removed, as entrypoint.sh in Dockerfile now handles the start command
    #   - start
    networks:
      - diplom_default
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    restart: unless-stopped

volumes:
  keycloak_postgres_data:

networks:
  diplom_default:
    name: diplom_default
    external: true
