services:
  keycloak-postgres:
    image: postgres:latest
    container_name: keycloak-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=${KC_DB}
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
    ports:
      - "${KEYCLOAK_PORT}:8080"
    depends_on:
      - keycloak-postgres
      - mailhog
    command:
      - start-dev
    networks:
      - keycloak-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: keycloak-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - keycloak-network

volumes:
  keycloak_postgres_data:

networks:
  keycloak-network:
    driver: bridge
