version: '3.8'

services:
  seller-app:
    build: .
    ports:
      - "3003:80" # Маппинг порта хоста 3003 на порт контейнера 80
    volumes:
      - .:/app # Опционально: для разработки, чтобы изменения в коде отражались в контейнере
      - /app/node_modules # Исключаем node_modules из volume, чтобы использовать установленные в Dockerfile
    environment:
      - NODE_ENV=development # Или production, в зависимости от ваших нужд
      # Добавьте другие переменные окружения, если необходимо
      # Например, URL вашего Keycloak сервера, realm, client ID
      # - REACT_APP_KEYCLOAK_URL=http://localhost:8080/auth
      # - REACT_APP_KEYCLOAK_REALM=myrealm
      # - REACT_APP_KEYCLOAK_CLIENT_ID=myclient