services:
  seller-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_SELLER_PORT:-8081}:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8000}
    networks:
      - default
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  default:
    name: diplom_default
    external: true
