version: '3.8'

services:
  seller-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: seller-frontend-dev
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=${FRONTEND_SELLER_PORT:-3000}
    ports:
      - "${FRONTEND_SELLER_PORT:-3000}:3000"
    restart: unless-stopped
    networks:
      - frontend-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  frontend-network:
    external: true
