services:
  seller-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
        REACT_APP_WOODEN_BOARDS_API_URL: ${REACT_APP_WOODEN_BOARDS_API_URL}
    container_name: ${SELLER_FRONTEND_CONTAINER:-seller-frontend-prod}
    ports:
      - "${SELLER_FRONTEND_PORT:-8081}:80"
    networks:
      - diplom_default
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

networks:
  diplom_default:
    name: diplom_default
    external: true
