version: '3.8'

services:
  # Selenium Hub для координации браузеров
  selenium-hub:
    image: selenium/hub:4.15.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"
    environment:
      - GRID_MAX_SESSION=16
      - GRID_BROWSER_TIMEOUT=300
      - GRID_TIMEOUT=300
      - SE_SESSION_REQUEST_TIMEOUT=300
      - SE_SESSION_RETRY_INTERVAL=5
    networks:
      - test_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Chrome браузер для тестирования
  selenium-chrome:
    image: selenium/node-chrome:4.15.0
    container_name: selenium-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_VNC_PASSWORD=secret
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - test_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/wd/hub/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Firefox браузер для кросс-браузерного тестирования
  selenium-firefox:
    image: selenium/node-firefox:4.15.0
    container_name: selenium-firefox
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_VNC_PASSWORD=secret
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - test_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/wd/hub/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Edge браузер для дополнительного покрытия
  selenium-edge:
    image: selenium/node-edge:4.15.0
    container_name: selenium-edge
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=2
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_VNC_PASSWORD=secret
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - test_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555/wd/hub/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Тестовый контейнер для запуска Selenium тестов
  selenium-tests:
    build:
      context: .
      dockerfile: Dockerfile.selenium
    container_name: selenium-tests
    depends_on:
      selenium-hub:
        condition: service_healthy
      selenium-chrome:
        condition: service_healthy
      selenium-firefox:
        condition: service_healthy
    environment:
      - SELENIUM_HUB_URL=http://selenium-hub:4444/wd/hub
      - FRONTEND_ADMIN_URL=http://admin-frontend:80
      - FRONTEND_SELLER_URL=http://seller-frontend:80
      - FRONTEND_BUYER_URL=http://buyer-frontend:80
      - BACKEND_API_URL=http://test-backend:8000
      - PYTHONPATH=/app
      - PYTEST_TIMEOUT=300
    volumes:
      - .:/app
      - ./screenshots:/app/screenshots
      - ./test-reports:/app/test-reports
    working_dir: /app
    networks:
      - test_network
    command: >
      bash -c "
        echo 'Waiting for Selenium Grid to be ready...' &&
        sleep 30 &&
        echo 'Starting Selenium tests...' &&
        python -m pytest browser_tests/ 
          --tb=short 
          --maxfail=5 
          --timeout=300 
          --html=test-reports/selenium-report.html 
          --self-contained-html 
          --junitxml=test-reports/selenium-junit.xml 
          -v
      "

  # VNC Viewer для отладки (опционально)
  selenium-vnc-chrome:
    image: selenium/node-chrome:4.15.0
    container_name: selenium-vnc-chrome
    depends_on:
      - selenium-hub
    ports:
      - "5900:5900"  # VNC порт для Chrome
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
      - SE_VNC_PASSWORD=secret
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - test_network
    profiles:
      - debug

  selenium-vnc-firefox:
    image: selenium/node-firefox:4.15.0
    container_name: selenium-vnc-firefox
    depends_on:
      - selenium-hub
    ports:
      - "5901:5900"  # VNC порт для Firefox
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
      - SE_VNC_PASSWORD=secret
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - test_network
    profiles:
      - debug

networks:
  test_network:
    name: diplom-functional-tests_test_network
    external: true

volumes:
  selenium_screenshots:
    driver: local
  selenium_reports:
    driver: local
