services:
  admin-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: admin-frontend
    ports:
      - "${FRONTEND_ADMIN_PORT:-8080}:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8000}
    networks:
      - diplom_default
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

networks:
  diplom_default:
    external: true
