services:
  admin-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
    container_name: admin-frontend
    ports:
      - "${FRONTEND_ADMIN_PORT:-8080}:80"
    networks:
      - diplom_default
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always

networks:
  diplom_default:
    name: diplom_default
    external: true
